In [1]:
import numpy as np

In [6]:
a = np.zeros([9,9])
b = np.ones([2,2])
c = np.ones([3,6])
print(a,b,c)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]] [[1. 1.]
 [1. 1.]] [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [13]:
with open('toy_data.txt') as f:
    data = f.readlines()
data = [d.strip('\n') for d in data]

In [14]:
data

['0,9 -> 5,9',
 '8,0 -> 0,8',
 '9,4 -> 3,4',
 '2,2 -> 2,1',
 '7,0 -> 7,4',
 '6,4 -> 2,0',
 '0,9 -> 2,9',
 '3,4 -> 1,4',
 '0,0 -> 8,8',
 '5,5 -> 8,2']

In [15]:
for d in data:
    print(d.split(' -> '))

['0,9', '5,9']
['8,0', '0,8']
['9,4', '3,4']
['2,2', '2,1']
['7,0', '7,4']
['6,4', '2,0']
['0,9', '2,9']
['3,4', '1,4']
['0,0', '8,8']
['5,5', '8,2']


In [16]:
data = [d.split(' -> ') for d in data]

In [17]:
data

[['0,9', '5,9'],
 ['8,0', '0,8'],
 ['9,4', '3,4'],
 ['2,2', '2,1'],
 ['7,0', '7,4'],
 ['6,4', '2,0'],
 ['0,9', '2,9'],
 ['3,4', '1,4'],
 ['0,0', '8,8'],
 ['5,5', '8,2']]

In [18]:
for d in data:
    print("from ",d[0].split(',')," to ",d[1].split(','))

from  ['0', '9']  to  ['5', '9']
from  ['8', '0']  to  ['0', '8']
from  ['9', '4']  to  ['3', '4']
from  ['2', '2']  to  ['2', '1']
from  ['7', '0']  to  ['7', '4']
from  ['6', '4']  to  ['2', '0']
from  ['0', '9']  to  ['2', '9']
from  ['3', '4']  to  ['1', '4']
from  ['0', '0']  to  ['8', '8']
from  ['5', '5']  to  ['8', '2']


In [5]:
count = 0
for row in np.eye(3):
    for el in row:
        if el > 0:
            count+=1
print(count)

3
